"""
Confidence scoring and transparency label generation.

Combines the two signal scores into a single confidence score and maps it
to one of three attribution tiers with a plain-language transparency label.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Thresholds (from planning.md)
# ---------------------------------------------------------------------------
# >= 0.75  → likely_ai
# 0.45–0.74 → uncertain
# < 0.45   → likely_human
THRESHOLD_AI = 0.75
THRESHOLD_HUMAN = 0.45

# Signal weights
WEIGHT_LLM = 0.55
WEIGHT_STYLO = 0.45


def combine_scores(llm_score: float, stylo_score: float) -> float:
    """
    Combine signal scores into a single confidence score (0.0–1.0).

    Args:
        llm_score:   LLM signal output (1.0 = confident AI).
        stylo_score: Stylometric signal output (1.0 = AI-like statistics).

    Returns:
        Combined confidence score; higher = more likely AI-generated.
    """
    combined = WEIGHT_LLM * llm_score + WEIGHT_STYLO * stylo_score
    return round(max(0.0, min(1.0, combined)), 4)


def get_attribution(confidence: float) -> str:
    """
    Map a confidence score to an attribution tier.

    Returns one of: "likely_ai", "uncertain", "likely_human".
    """
    if confidence >= THRESHOLD_AI:
        return "likely_ai"
    elif confidence >= THRESHOLD_HUMAN:
        return "uncertain"
    else:
        return "likely_human"


def generate_label(confidence: float, attribution: str) -> str:
    """
    Generate the plain-language transparency label shown to readers.

    Three variants based on confidence tier:
      - likely_ai    (confidence >= 0.75): High-confidence AI label
      - uncertain    (0.45 <= conf < 0.75): Uncertain label
      - likely_human (confidence < 0.45): High-confidence human label

    Args:
        confidence:  The combined confidence score (0.0–1.0).
        attribution: The attribution tier string.

    Returns:
        Full label text as a multi-line string.
    """
    score_pct = round(confidence * 100)

    if attribution == "likely_ai":
        return (
            "⚠️ AI-Generated Content Detected\n\n"
            "Our analysis suggests this content was likely generated by an AI tool, "
            "not written by a human author.\n\n"
            f"Confidence: High ({score_pct}%)\n\n"
            "This label is shown to help readers understand the origin of this content. "
            "If you are the creator and believe this is incorrect, you may submit an appeal below."
        )
    elif attribution == "uncertain":
        return (
            "🔍 Origin Uncertain\n\n"
            "Our system was unable to determine with confidence whether this content "
            "was written by a human or generated by AI.\n\n"
            f"Confidence in AI origin: Moderate ({score_pct}%)\n\n"
            "We don't have enough signal to make a definitive determination. "
            "Readers should consider this context. "
            "Creators who believe this result is inaccurate may submit an appeal."
        )
    else:  # likely_human
        human_pct = round((1.0 - confidence) * 100)
        return (
            "✅ Likely Human-Written\n\n"
            "Our analysis suggests this content was written by a human author.\n\n"
            f"Confidence in human origin: High ({human_pct}%)\n\n"
            "This content passed our AI-origin detection checks. "
            "This label does not constitute a guarantee of authenticity."
        )
