"""
Signal 1: LLM-based classification via Groq.

Sends the text to llama-3.3-70b-versatile with a structured prompt that asks
the model to estimate the probability that the text was AI-generated.

Returns a float 0.0–1.0:
  1.0 = highly confident the text is AI-generated
  0.0 = highly confident the text is human-written
"""

import json
import os

from groq import Groq

_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise ValueError("GROQ_API_KEY is not set in environment variables.")
        _client = Groq(api_key=api_key)
    return _client


SYSTEM_PROMPT = """\
You are an expert forensic text analyst. Your job is to assess whether a given piece of text
was written by a human or generated by an AI language model.

Analyze the text for:
- Sentence structure uniformity (AI text is often very uniform)
- Vocabulary diversity and natural variation (humans vary more)
- Presence of hedging phrases typical of AI: "it is important to note", "furthermore", "it is worth mentioning"
- Personal voice, idiosyncrasies, tangents, contradictions (typically human)
- Overly clean transitions and balanced paragraphs (often AI)
- Emotional authenticity vs. performed emotion

Return ONLY valid JSON with exactly these two fields:
{
  "score": <float between 0.0 and 1.0>,
  "reasoning": "<one sentence explanation>"
}

Where score = 1.0 means you are certain the text is AI-generated, and score = 0.0 means you are certain it is human-written.
Do not include any text outside the JSON object.
"""


def groq_classify(text: str) -> tuple[float, str]:
    """
    Classify text using Groq LLM.

    Args:
        text: The text to classify. Will be truncated to 3000 chars if longer.

    Returns:
        (score, reasoning) where score is 0.0–1.0 (1.0 = AI-generated).

    Raises:
        RuntimeError: If the API call fails or response cannot be parsed.
    """
    # Truncate very long inputs — sample beginning + middle + end
    max_chars = 3000
    if len(text) > max_chars:
        chunk = max_chars // 3
        text = (
            text[:chunk]
            + "\n...[truncated for analysis]...\n"
            + text[len(text) // 2 : len(text) // 2 + chunk]
            + "\n...[truncated for analysis]...\n"
            + text[-chunk:]
        )

    client = _get_client()

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
            temperature=0.1,  # Low temperature for consistent scoring
            max_tokens=200,
        )
    except Exception as exc:
        raise RuntimeError(f"Groq API call failed: {exc}") from exc

    raw = response.choices[0].message.content.strip()

    # Strip markdown code fences if the model wraps in ```json ... ```
    if raw.startswith("```"):
        lines = raw.splitlines()
        raw = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

    try:
        parsed = json.loads(raw)
        score = float(parsed["score"])
        reasoning = str(parsed.get("reasoning", ""))
    except (json.JSONDecodeError, KeyError, ValueError) as exc:
        raise RuntimeError(f"Could not parse LLM response: {raw!r}") from exc

    # Clamp to [0.0, 1.0]
    score = max(0.0, min(1.0, score))
    return score, reasoning
